apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nginx-ingress-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.20.0.10-172.20.0.20
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: nginx-ingress-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - nginx-ingress-pool
